### ISSUE TITLE
Incorrect entity insertion

### ISSUE THREAD

**Issue by netcarver** [SimGus/Chatette#11]
Given this file...

```
%[ask_phone_number]
    {what is/tell/display} your @[number_type] number

@[number_type]
    direct
    tel
    telephone
```
I get JSON with one of the entities marked at the wrong place. Here's one example...
```
      {
        "entities": [
          {
            "end": 3,
            "entity": "number_type",
            "start": 0,
            "value": "tel"
          }
        ],
        "intent": "ask_phone_number",
        "text": "tell your tel num"
      },
```

To ease diagnosing the issue, I've passed the generated JSON through ```rasa_nlu.convert``` to get markdown (which makes it more obvious)...

```
what is your [direct](number_type) number
what is your [tel](number_type) number
what is your [telephone](number_type) number
tell your [direct](number_type) number
[tel](number_type)l your tel number              <<< Erroneous output
tell your [telephone](number_type) number
display your [direct](number_type) number
display your [tel](number_type) number
display your [telephone](number_type) number
```

This seems to happen when one of the example entity strings under a slot definition occurs as a sub-string earlier in the generated text than the position that actually needs to be targeted.

Guessing that a ```\b``` might need adding to a regex somewhere to ensure any entity value substitutions happen on word boundaries.

Many thanks for your consideration.

**Comment by SimGus** [comment]
That might happen indeed, I didn't think of that possibility when programming this. I'll fix that as soon as I can (I don't have much time at the moment sorry).

Thanks a lot for submitting a bug report :)

**Comment by SimGus** [comment]
I just fixed this. It should work now in all cases (unless you use the string `<<CHATETTE_ENTITY>>` within your generated examples).
The fix is available on the branch `dev` and will be available on PyPI on the next release.

Thanks again for the report
