### ISSUE TITLE
-o/--out command line parameter not work

### ISSUE THREAD

**Issue by iorilu** [SimGus/Chatette#12]
I checked the source code , it seems not use the parameter , always use "output"

`   
 dir_path = os.path.join(dir_path, "output")
`

**Comment by SimGus** [comment]
Indeed, it's a mistake. I will fix it ASAP.

Thanks a lot for the report.

**Comment by SimGus** [comment]
It is now fixed on branch [`dev`](https://github.com/SimGus/Chatette/tree/dev) and will be merged back into [`master`](https://github.com/SimGus/Chatette) and on [PyPI](https://pypi.org/project/chatette) when the next update is released.

**Comment by SimGus** [comment]
This issue is now fixed in v1.3.2 (available on [PyPI](https://pypi.org/project/chatette)).

Thanks again for the report.
