### ISSUE TITLE
Error if alias is not defined

### ISSUE THREAD

**Issue by zenhaust** [SimGus/Chatette#13]
I want to say is that this is a great work. And I apologize for my poor English.

Well, if the alias don´t exists, the system should must take the text between the square brackets.
Now I catch error.

Example:
busca**~[me]** un buen restaurante

`...
    
nb_possible_ex = self.parser.get_definition(self.name, Unit.alias) \
  File "/site-packages/chatette/parsing.py", line 454, in get_definition
    def_name + "'")

ValueError: Couldn't find a definition for alias 'me'
`

Best regards.

**Comment by SimGus** [comment]
Hello,

This is actually the intended behavior: if you reference an alias, it *has to be defined* somewhere.
If you want the word in-between the brackets to be used, you have to use a word group. Your example would thus become:
```
busca**[me]** un buen restaurante
```
This will generate this example: `busca**me** un buen restaurante` (and only this one).

This is explained in the [syntax specifications](https://github.com/SimGus/Chatette/blob/master/syntax-specs.md) (and I am making a wiki to improve the documentation). You can also look into the examples on this repo (notably the one in `examples/simple/restaurant` which looks similar to what you seem to be doing).

Regards
