### ISSUE TITLE
Bug with file paths when including files

### ISSUE THREAD

**Issue by algomax** [SimGus/Chatette#15]
Hi,

FIrst of all, thank you for the excellent tool, I love it!

I noticed the following issue starting from 1.4.0. If you include a file that includes other files, those other files are assumed to be in the same folder as the initial main file.

Assume the following file structure:
/path1/main.chatette - includes /path2/shared.chatette
/path2/shared.chatette - includes /path2/aliases.chatette
/path2/aliases.chatette

If we try to generate examples using main.chatette, in this scenario, Chatette will look for the aliases.chatette file in /path1/ and not in /path2/, which is incorrect and throws an error.

Thanks!
Martin

**Comment by SimGus** [comment]
You're right, I didn't think of that case when I refactored this part of the code.
I'll fix that as soon as I can.

Thank you for the bug report.

**Comment by SimGus** [comment]
This should be fixed now. I'll release a new version with this bugfix in it.

Thanks again for the bug report.
