### ISSUE TITLE
Support for passing configuration file from command arguments

### ISSUE THREAD

**Issue by libindavis** [SimGus/Chatette#16]
It would be great if Chatette could support passing configuration JSON file with Rasa options from command arguments. 

Here is an example for the configuration JSON file. 
```    
      1  {
      2     "rasa_nlu_data": {
      3         "regex_features": [
      4         {
      5             "name": "tier_pattern",
      6             "pattern": "tier[_\\-\\s]*\\d+\\.?\\d*"
      7         },
      8         ]
      9     }
     10 }
```

**Comment by SimGus** [comment]
Hello,

Do you mean you would like Chatette to add the generated examples (and synonyms) into a custom JSON object, and provide the custom JSON in a file referenced using command line options? Or did I misunderstand what you meant?

As a side note, I'm planning to add support for Rasa regexes as some point (not now since I don't have much time atm).

**Comment by libindavis** [comment]
Yes. 

In RASA JSON file, there are 4 important fields: common_examples, regex_patterns, lookup_tables, entity_synonyms.  Chatette could only generates the 'common_examples' field with some real values, while the other three fields are left to be empty.   
Chatitto now supports an optional option  **'<formatOptions>'**  to specify a custom JSON file that each user could declare their own  fields of 'regex_pattern' and 'lookup_table'. 

https://github.com/rodrigopivi/Chatito/issues/20#issuecomment-396333978

**Comment by SimGus** [comment]
Okay, I see. This shouldn't be too hard to make.
I'll add that as soon as I can ;)

Just so you know, Chatette also support entity synonyms (see [the end of this section in the documentation](https://github.com/SimGus/Chatette/wiki/Units#slot)). Entity synonyms are automatically computed.

**Comment by libindavis** [comment]
Yes, it should be easy.  I updated locally to implement it.

**Comment by SimGus** [comment]
Support for this has been added in v1.5.0. You can use the command line option `--base-file` to provide *Chatette* a base file that will be extended, as described [here](https://github.com/SimGus/Chatette/wiki/Files-organization#base-file). This currently works only with the *Rasa* adapter.

Sorry for taking so long to add this, I've been very busy.
