### ISSUE TITLE
Chatette removes output folder

### ISSUE THREAD

**Issue by alexeykarnachev** [SimGus/Chatette#18]
Hello! I've faced with issue: 
`
python -m chatette template/path -o output/dir
`
It removes `output/dir`
Please, check lines 96-97 in `facade.py`
I think it's very strange and dangerous behavior
 
https://github.com/SimGus/Chatette/blob/master/chatette/facade.py#L96

Thank you

**Comment by SimGus** [comment]
That may indeed be an issue in some cases. I'll fix that when I have time.

Thanks for the heads up :)

**Comment by SimGus** [comment]
This is fixed in v1.5.0: *Chatette* will ask for confirmation before overwriting the output folder (if it existed). If you need to get the same behavior as before (i.e. no confirmation), use the `-f`/`--force` command line option.
