### ISSUE TITLE
Named random generation modifiers not working properly

### ISSUE THREAD

**Issue by hatrungduc** [SimGus/Chatette#19]
Hello,

I am encountering an issue with Chatette v1.5.0 PyPI (installed via pip).

Rule: `I don't like [world?WWII] war[ II?WWII].`  

Expected examples:

- I don't like war.
- I don't like world war II.

Generated examples:
- I don't like war.
- I don't like war II.
- I don't like world war.
- I don't like world war II.

I tested it with a .chatette file and the interactive console. Both methods generate the same sentences.

**Comment by SimGus** [comment]
There is indeed a bug. I'll try to fix that as soon as possible.

Thanks for the heads up :)

**Comment by SimGus** [comment]
I can see why this problem is occurring. However, this would need quite a lot of changes on the problematic code, and since I am in the middle of a refactor of this code, I will not fix it right now. This will be fixed as soon as the refactor is over (which I hope doesn't take too long).

**Comment by hatrungduc** [comment]
That's ok, good luck on the refactor!

**Comment by SimGus** [comment]
This is (finally) fixed in the latest version (v1.6.0) :)
