### ISSUE TITLE
Incorrect entity position in rasa adapter

### ISSUE THREAD

**Issue by hungph-dev-ict** [SimGus/Chatette#22]
{
       "entities": [
         {
           "end": 112,
           "entity": "bot_job",
           "start": 93,
           "value": "sứ mệnh như thế nào"
         }
       ],
       "intent": "ask_for_bot_job",
       "text": "xếp sứ mệnh như thế nào"
     },

The 1.6.0 version and I are having the error of generating the wrong locations of entities in the sentence, above is an example. Please check again! Thank you

**Comment by SimGus** [comment]
I cannot reproduce this bug, I get the following output:
```json
    {
        "entities": [
          {
            "end": 23, 
            "entity": "slot", 
            "start": 4, 
            "value": "sứ mệnh như thế nào"
          }
        ], 
        "intent": "intent", 
        "text": "xếp sứ mệnh như thế nào"
      }
```

Are you using a different file encoding than UTF-8? (this is likely the case if you're using Windows.) Chatette should always work well with Unicode files.

If this is not an encoding problem, could you provide the template you used to get this output please?

**Comment by devdeca** [comment]
I'm having the same problem, the file encode is us-ascii.
It is also interesting notice that if I configure the training down to 1 or 2, the generation works out fine, but as I raised its value, the result became like showed below.

My template:

`%[askPopulation]('training': '5')
    ~[greet?] ~[population] @[city]

@[city]
    new york
    tokyo

~[greet]
    hi
    hello

~[population]
    what is the population of
    how many people are there in
`
The output:

`{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "entities": [
          {
            "end": 183,
            "entity": "city",
            "start": 178,
            "value": "tokyo"
          }
        ],
        "intent": "askPopulation",
        "text": "how many people are there in tokyo"
      },
      {
        "entities": [
          {
            "end": 186,
            "entity": "city",
            "start": 178,
            "value": "new york"
          }
        ],
        "intent": "askPopulation",
        "text": "hello what is the population of new york"
      },
      {
        "entities": [
          {
            "end": 183,
            "entity": "city",
            "start": 178,
            "value": "tokyo"
          }
        ],
        "intent": "askPopulation",
        "text": "what is the population of tokyo"
      },
      {
        "entities": [
          {
            "end": 186,
            "entity": "city",
            "start": 178,
            "value": "new york"
          }
        ],
        "intent": "askPopulation",
        "text": "how many people are there in new york"
      },
      {
        "entities": [
          {
            "end": 186,
            "entity": "city",
            "start": 178,
            "value": "new york"
          }
        ],
        "intent": "askPopulation",
        "text": "what is the population of new york"
      }
    ],
    "entity_synonyms": [],
    "lookup_tables": [],
    "regex_features": []
  }
}`

**Comment by SimGus** [comment]
There is a problem indeed. It doesn't seem related to encoding. I'll fix that as soon as I can.

Thanks for the heads up :)

**Comment by SimGus** [comment]
This is fixed on master branch. The fix will be present in the next release.

Cheers

**Comment by SimGus** [comment]
The newest version of Chatette (v1.6.1) has just been released with this bug fixed!
