### ISSUE TITLE
Bug in chatette.parsing.utils

### ISSUE THREAD

**Issue by IngerMathilde** [SimGus/Chatette#27]
First of all really nice library! I did however notice a small bug in the chatette.parsing.utils file

On line 49-56 it states the following:
escapable_chars = [
    ESCAPEMENT_SYM,
    COMMENT_SYM, OLD_COMMENT_SYM,
    UNIT_START_SYM, UNIT_START_SYM,
    RAND_GEN_SYM, RAND_GEN_PERCENT_SYM,
    VARIATION_SYM,
    ARG_SYM,
    CASE_GEN_SYM,
]

However, line 52 repeats UNIT_START_SYM, UNIT_START_SYM twice. Instead it the second instance should be replaced with UNIT_END_SYM. 

Thus it should be
escapable_chars = [
    ESCAPEMENT_SYM,
    COMMENT_SYM, OLD_COMMENT_SYM,
    UNIT_START_SYM, UNIT_END_SYM,
    RAND_GEN_SYM, RAND_GEN_PERCENT_SYM,
    VARIATION_SYM,
    ARG_SYM,
    CASE_GEN_SYM,
]

**Comment by SimGus** [comment]
Hello,

Thanks a lot for this very precise bug report :)
I'm fixing this right away. I'll also turn that list into a set, as it is never iterated over.

**Comment by SimGus** [comment]
This is fixed on `dev` branch and will be included in the next release.

Thanks again for the heads up!
