### ISSUE TITLE
Error on second run within same script

### ISSUE THREAD

**Issue by KendallPruitt** [SimGus/Chatette#28]
There seems to be an issue when running chatette more than once in a single script. Even when we reset either the instance or the system, it throws a syntax error like:
`SyntaxError: Tried to declare intent 'E7WzqixfmcHF1zAvsE9LIbEL450pPHOe' twice.`
It always works the first time, but even though we give it a random intent name every time, it thinks it's already been declared.

I've tried deleting the facade object as well as reloading the chatette library altogether, but I still can't avoid the error.

chatetteTest.txt is the python script I'm using to test it and common.txt is a required grammar file to run it.
Any help you could provide on this would be greatly appreciated.

[chatetteTest.txt](https://github.com/SimGus/Chatette/files/3858595/chatetteTest.txt)

[common.txt](https://github.com/SimGus/Chatette/files/3858598/common.txt)

**Comment by SimGus** [comment]
I'll check that out as soon as I can. Thanks for providing your files :)

**Comment by SimGus** [comment]
This is fixed on the `dev` branch. It should be included in the next release.

Thanks again for raising this issue!
