### ISSUE TITLE
To control the data generate

### ISSUE THREAD

**Issue by githubclj** [SimGus/Chatette#3]
When i run the run.py for twice,can you make sure that generated data are the same

**Comment by SimGus** [comment]
The generation relies on random number generation and is different on different executions because of that.
Anyway, I think it is a good idea to add what you propose. I will look into adding a seed when I have the time ;)

**Comment by SimGus** [comment]
There you go.
You can use `-s` or `--seed` followed by any string you like (without spaces) to set the generator seed. If you execute the script several times on the same template with the same seed, the data generated should be exactly the same.
The package has been updated on PyPI too, so you can simply download it from there (`pip install chatette`).
