### ISSUE TITLE
KeyError: "Didn't expect the random generation name 'WWII' to already be set (for example with text '')."

### ISSUE THREAD

**Issue by mfxss** [SimGus/Chatette#31]
The rule "I don't like [world?WWII] war[II?WWII]." lead to the error.
It seems there is something wrong with Named random generation.

**Comment by SimGus** [comment]
There is an issue indeed. I am checking that up as soon as possible.

Thanks for the heads up!

**Comment by SimGus** [comment]
This is fixed on `dev` branch and will be released in the next version.

Thanks again for opening an issue :)
