### ISSUE TITLE
"end-index" support for JSONL adapter

### ISSUE THREAD

**Issue by ValentinCalomme** [SimGus/Chatette#32]
Currently, generating examples using the JSONL adapter provides the following fields for each slot: start-index, text, and slot-name. For instance:

```python
{
    "slot-name": "PER",
    "value": "Albert Einstein",
    "start-index": 0
}
```

At this point, if I want to infer the span of slot (i.e., to pass it along to SpaCy's NER), I can find the end-index by summing the length of the value and the start index.

While this is fine when no specific value is provided, when a value is provided for the slot, it becomes impossible to know for sure what is the span of the slot. For instance, if "Albert Einstein" is equal to some concept ID in a knowledge base:

```python
{
    "slot-name": "PER",
    "value": "KB4245435",
    "start-index": 0
}
```

It could be potentially doable to go through the generated synonyms, but this seems to be way harder than it needs to be. What I propose is the addition of a `end-index` field, as follows:

```python
{
    "slot-name": "PER",
    "value": "KB4245435",
    "start-index": 0,
    "end-index":  15
}
```

**Comment by SimGus** [comment]
This is indeed a very good argument for the end index to be included in slots representations.
It actually used to be contained in those objects, but I removed it in v1.6.0 because it was not useful in the code any longer.

I'll review your pull request right away. Thank you for making it :)

**Comment by ValentinCalomme** [comment]
No problem! Thanks a lot for spending time working on the library, I am using it quite often lately and will continue to contribute to it anyway I can!

**Comment by SimGus** [comment]
This is merged in `dev` branch and will be part of the next patch release :)
