### ISSUE TITLE
wiki improvement: `|` should be escaped

### ISSUE THREAD

**Issue by xuchen** [SimGus/Chatette#36]
Can't submit a PR to wiki so I'll just write here:

```
Here are all the characters that should be escaped if you want to use them in a unit identifier (i.e. use \; instead of ,): ?, ;, /, //, #, $, &, [ and ].
```
from https://github.com/SimGus/Chatette/wiki/Quickstart

You missed `|`. ;-)

**Comment by SimGus** [comment]
Oh you're right, this list is not up to date with the list in https://github.com/SimGus/Chatette/wiki/Generation-rules
I'll fix that.

Thanks a lot! :)

**Comment by SimGus** [comment]
This is fixed. Thanks again :)

On another note, I'll see if I can make up a system to let people contribute to the wiki.
