### ISSUE TITLE
random generation of a content of my training data

### ISSUE THREAD

**Issue by Asma-droid** [SimGus/Chatette#39]
Hi all,

I'am in Linux with multi-processeurs  and i have configurated my chatette.py as follows: 

```python
from chatette.facade import Facade
import sys
facade = Facade(sys.argv[1], sys.argv[2], "rasamd", seed='ljjeek', force_overwriting=True)
facade.run()
```

My problem is that chatette run in // with a random manner. If i launch two times chatette. 

The first Time i obtain:
## intent: intent 3

The second time i obtain:
## intent: intent 2

So the order of the intents is not the same. Is there a solution to fix this issue ?

Thanks

**Comment by SimGus** [comment]
Hello,

Thanks for pointing this out.
It looks like a bug, but I am unable to reproduce it: running your code and using [the airport example](https://github.com/SimGus/Chatette/tree/master/examples/simple/airport) as a template always generates an output with the intents in the same order.

Would you mind posting the template file you used here?

Also, could you explain why it's important for you to have intents always generated in the same order?

Thanks in advance :)

**Comment by SimGus** [comment]
I'll close this since I got no response and can't reproduce it.

Feel free to reopen it if you can give me more information.
