### ISSUE TITLE
how do we output a markdown format file instead of json?

### ISSUE THREAD

**Issue by naikshubham** [SimGus/Chatette#41]

**Comment by SimGus** [comment]
Hello!

To output both your training and test files to Rasa NLU markdown format, you need to use the value `rasamd` or `rasa-md` for the adapter.

In your terminal, you would thus call the program in the following way:
```sh
python -m chatette -a rasamd
```
or
```sh
python -m chatette --adapter rasa-md
```

This is not up-to-date in the help string of the program (`python -m chatette -h`) nor in the wiki, sorry about that. I'll update this as soon as I can.

**Comment by SimGus** [comment]
I just updated the [documentation](https://github.com/SimGus/Chatette/wiki/Command-line-interface) to include the newest adapter. I also made some changes to the main help of the program. If you are using Chatette from PyPI, you'll be able to see this when I release a new version of the program.

Thanks for the heads up!

**Comment by naikshubham** [comment]
> Hello!
> 
> To output both your training and test files to Rasa NLU markdown format, you need to use the value `rasamd` or `rasa-md` for the adapter.
> 
> In your terminal, you would thus call the program in the following way:
> 
> ```shell
> python -m chatette -a rasamd
> ```
> 
> or
> 
> ```shell
> python -m chatette --adapter rasa-md
> ```
> 
> This is not up-to-date in the wiki, sorry about that. I'll update this as soon as I can. It can be seen in the main help of the program (`python -m chatette -h`) if you are using the latest version in the `master` branch.

Thanks @SimGus
