### ISSUE TITLE
Randomly pick few variations from each intent example instead of all varations. 

### ISSUE THREAD

**Issue by dingusagar** [SimGus/Chatette#51]
After writing the template files and generating a huge output file, i realised that i just dont need all possible combinations. 
is there any way we can randomly sample variatons from each intent example. 

for example if I have an intent defined like this. 

%[greet user]
   ~[greeting] user! What is your @[operating system]?
    ~[greeting]  What is the name of your @[operating system]?  

instead of generating all possible variations for these intents, if I can control the number of variations from each sentence under every intent, something like ouput only 25% variations from each sentence by random sampling. 

This would make my output files smaller and at the same time cover most of the variations. 

Just wanted to know if I can acheive something like this using the existing features. This feature would be really helpful.

**Comment by SimGus** [comment]
Hello, thanks for your question!

This is a feature that actually exists: you can ask for a specific number of examples to be generated.

You would do this in the following way:
```
%[greet user](12)
   ~[greeting] user! What is your @[operating system]?
   ~[greeting] What is the name of your @[operating system]?
```
Note the `(12)` right after the intent declaration. As you can expect, this will generate 12 different examples for this intent (or fewer if all combination represent fewer than 12 examples).

About asking for a percentage of all possibilities for an intent on the other hand, this feature is not implemented, but I have plans to add it.

I hope this clears it up for you!
I'll close the issue but feel free to ask for more details here if needed. You can also find more information in the wiki.

**Comment by dingusagar** [comment]
totally missed this feature when I was reading the wiki pages. this is super helpful! thanks
